### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'twitch_proxy_playlist'

### ISSUE THREAD

**Issue by brian6932** [2bc4/streamlink-ttvlol#59]
New issue with `streamlink 6.6.2+1.gf205f54`
```
❯ streamlink twitch.tv/channel best
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "~\scoop\apps\streamlink-nightly-lean-ttv-lol\current\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "~\scoop\apps\streamlink-nightly-lean-ttv-lol\current\pkgs\streamlink_cli\main.py", line 933, in main
    handle_url()
  File "~\scoop\apps\streamlink-nightly-lean-ttv-lol\current\pkgs\streamlink_cli\main.py", line 543, in handle_url
    options = setup_plugin_options(pluginname, pluginclass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\scoop\apps\streamlink-nightly-lean-ttv-lol\current\pkgs\streamlink_cli\main.py", line 749, in setup_plugin_options
    value = getattr(args, parg.namespace_dest(pluginname))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'twitch_proxy_playlist'
```

**Comment by Sokoloft** [comment]
Try stable branch of streamlink. You're using nightly

**Comment by Sokoloft** [comment]
Also issue looks similar to #58 , make sure you have it in the correct dir that the readme says.

**Comment by 2bc4** [comment]
I have no idea what they changed but replacing the twitch.py somehow doesn't work anymore. If you can change your scoop script to use sideloading that would work.

**Comment by brian6932** [comment]
> Try stable branch of streamlink. You're using nightly

I'm aware that, that can work, the point of the issue is nightly

**Comment by 2bc4** [comment]
Another solution could be to apply this diff from the streamlink root dir:
```
diff --git a/session/plugins.py b/session/plugins.py
index 5ef32d6..501d2ec 100644
--- a/session/plugins.py
+++ b/session/plugins.py
@@ -53,7 +53,7 @@ class StreamlinkPlugins:
     always have a higher priority than built-in plugins.
     """

-    def __init__(self, builtin: bool = True, lazy: bool = True):
+    def __init__(self, builtin: bool = True, lazy: bool = False):
         # Loaded plugins
         self._plugins: Dict[str, Type[Plugin]] = {}

```

But yeah there's no way to disable lazy loading from the twitch.py, you would have to handle it in the scoop script.
