### ISSUE TITLE
Does not work when opening streams through streamlink-twitch-gui v2.5.3

### ISSUE THREAD

**Issue by KaMyKaSii** [2bc4/streamlink-ttvlol#65]
Streamlink 7.0.0 and the streamlink-ttvlol 7.0.0 plugin work when calling streamlink through the terminal, but when using streamlink-twitch-gui v2.5.3 it is not possible to open any stream, returning the error below. I assume the problem is with the plugin because when removing it (rm /home/matheus/.local/share/streamlink/plugins/twitch.py), streamlink-twitch-gui v2.5.3 opens the streams normally.

```
Traceback (most recent call last):
File "/home/matheus/.local/bin/streamlink", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink_cli/main.py", line 1031, in main
setup(parser)
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink_cli/main.py", line 983, in setup
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink_cli/main.py", line 776, in setup_plugins
load_plugins(PLUGIN_DIRS, showwarning=False)
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink_cli/main.py", line 684, in load_plugins
success = streamlink.plugins.load_path(directory)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink/session/plugins.py", line 111, in load_path
plugins = self._load_plugins_from_path(path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink/session/plugins.py", line 183, in _load_plugins_from_path
lookup = self._load_plugin_from_finder(name, finder=finder) # type: ignore[arg-type]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink/session/plugins.py", line 199, in _load_plugin_from_finder
mod = exec_module(finder, f"streamlink.plugins.{name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/matheus/.local/lib/python3.12/site-packages/streamlink/utils/module.py", line 39, in exec_module
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/home/matheus/.local/share/streamlink/plugins/twitch.py", line 64, in <module>
@dataclass
^^^^^^^^^
File "/usr/lib/python3.12/dataclasses.py", line 1268, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/lib/python3.12/dataclasses.py", line 1258, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/dataclasses.py", line 983, in _process_class
and _is_type(type, cls, dataclasses, dataclasses.KW_ONLY,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/dataclasses.py", line 749, in _is_type
ns = sys.modules.get(cls.__module__).__dict__
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

**Comment by 2bc4** [comment]
Looking into it

**Comment by mjohnson9** [comment]
In case it helps diagnose: I ran into the same error, but on the command line.

Also running Linux; Streamlink 6.11.0; streamlink-ttvlol e0acf42; Python 3.12.7

**Comment by 2bc4** [comment]
Hmm I can only get this to happen if Streamlink is below version 7.0.0, on CLI or the GUI. Is it possible your GUI is set to use an older version (either through $PATH or manual)?

If you run the GUI with `--loglevel=debug` this should be in the terminal output:
```
[debug][StreamingService]
Validated streaming provider
{
    "version": "7.0.0"
}
```

**Comment by KaMyKaSii** [comment]
> Hmm I can only get this to happen if Streamlink is below version 7.0.0, on CLI or the GUI. Is it possible your GUI is set to use an older version (either through $PATH or manual)?
> 
> If you run the GUI with `--loglevel=debug` this should be in the terminal output:
> 
> ```
> [debug][StreamingService]
> Validated streaming provider
> {
>     "version": "7.0.0"
> }
> ```

You are right. I recently updated my KDE Neon distro, which updated its base to Ubuntu 24.04, which now requires the user to install python packages through [virtual environments.](https://packaging.python.org/en/latest/specifications/externally-managed-environments/#externally-managed-environments) Basically, I now have two streamlink installations, the old 6.11.0 in /home/matheus/.local/bin/streamlink and the new 7.0.0 in /home/matheus/.venv/bin/streamlink. I configured streamlink-twitch-gui to use the new installation in the Streamlink executable path and now it is working again. You can close the issue now if you think it is necessary. Thanks!

**Comment by mjohnson9** [comment]
It appears I had the same root cause. My Linux distribution updated to Streamlink 7.0.0 and e0acf42 now works for me.
